### PR TITLE
fix: removed unreached throw

### LINKED ISSUE #112: Non reached throw
https://github.com/kyranet/Sneyra/blob/9e2ec704f5fdd358f63095fce57dc6dbf927242b/src/lib/structures/MusicManager.js#L222

This throw will never happen, as the play command (referenced below) will run the join command before running MusicManager.play()

https://github.com/kyranet/Sneyra/blob/9e2ec704f5fdd358f63095fce57dc6dbf927242b/src/commands/Music/play.js#L15

### PR DESCRIPTION
**Pull request by PyroTechniac**
Fixes #112

### CODE REVIEW

**Comment by MrJacz** [comment]
This PR is incorrect

**Comment by PyroTechniac** [comment]
@MrJacz Can you elaborate further and I would be willing to fix?

**Comment by MrJacz** [comment]
This PR as a whole is incorrect. that if check if completely fine and reachable.

**Comment by PyroTechniac** [comment]
While it may be reachable, the command itself will never cause it to trigger. When the play command runs, it checks if it's in a voice channel, and if not runs the join command. Which means that the bot will always be in a voice channel before MusicManager.play() is called

**Comment by MrJacz** [comment]
@PyroTechniac you're assuming nothing will go wrong and everything before that will work

**Comment by PyroTechniac** [comment]
@MrJacz No, unless discord incorrectly reports that the bot joins the channel when it hasn't, then the previous checks will throw before this check is ever reached

**Comment by MrJacz** [comment]
@PyroTechniac You're removing a check for an edge case. I promise you its possible for it to happen as its happened to me before. No reason to remove an edge case that actually can happen.

**Pull request closed without merging**
